/**
 * HuggingFaceProvider — connects to the free Hugging Face Inference API.
 * Handles text-to-text (chat) and text-to-image (FLUX, SD) pipelines.
 * Models labelled with [Image Gen] return dynamic blobs!
 */
class HuggingFaceProvider {
  constructor(apiKey) {
    this.apiKey  = apiKey;
    this.baseURL = 'https://router.huggingface.co/hf-inference/models';
    this.name    = 'Hugging Face';
  }

  static get FREE_MODELS() {
    return [
      { id: 'hf-black-forest-labs/FLUX.1-schnell',   name: 'FLUX.1 Schnell [Image Gen]', supportsThinking: false, isImageGen: true, provider: 'Hugging Face' },
      { id: 'hf-meta-llama/Llama-3.2-11B-Vision-Instruct', name: 'Llama 3.2 11B Vision', supportsThinking: false, isImageGen: false, provider: 'Hugging Face' },
      { id: 'hf-Qwen/Qwen2.5-72B-Instruct',                name: 'Qwen 2.5 72B',         supportsThinking: false, isImageGen: false, provider: 'Hugging Face' },
      { id: 'hf-stabilityai/stable-diffusion-3.5-large',   name: 'Stable Diffusion 3.5 [Image Gen]', supportsThinking: false, isImageGen: true, provider: 'Hugging Face' }
    ];
  }

  // Helper to parse multimodal object back into text for HF if it's text-only or unsupported
  _extractText(content) {
    if (typeof content === 'string') return content;
    if (Array.isArray(content)) {
      return content.filter(c => c.type === 'text').map(c => c.text).join('\n');
    }
    return '';
  }

  async *stream(messages, options = {}) {
    const rawId = (options.model || 'hf-Qwen/Qwen2.5-72B-Instruct').replace('hf-', '');
    const modelDef = HuggingFaceProvider.FREE_MODELS.find(m => m.id === options.model || m.id === `hf-${rawId}`);
    
    // IMAGE GENERATION PIPELINE
    if (modelDef && modelDef.isImageGen) {
      yield* this._generateImage(rawId, messages, options);
      return;
    }

    // TEXT GENERATION PIPELINE (Serverless Chat Completions)
    yield* this._generateText(rawId, messages, options);
  }

  async *_generateImage(modelId, messages, options) {
    // Extract the very last user message for the image prompt
    const lastMsg = [...messages].reverse().find(m => m.role === 'user');
    const prompt = lastMsg ? this._extractText(lastMsg.content) : 'A beautiful landscape';

    yield { content: '*Generating image with ' + modelId + '...*\n\n' };

    const res = await fetch(`${this.baseURL}/${modelId}`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${this.apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ inputs: prompt }),
      signal: options.signal
    });

    if (!res.ok) {
      if (res.status === 503) {
        throw new Error('Model is currently loading (Cold Start). Wait a few seconds and try again.');
      }
      throw new Error(`Hugging Face API Error ${res.status}`);
    }

    // The endpoint returns binary image data
    const blob = await res.blob();
    const objectURL = URL.createObjectURL(blob);
    
    yield { content: `![Generated by ${modelId}](${objectURL})\n` };
  }

  async *_generateText(modelId, rawMessages, options) {
    // HuggingFace's chat/completions endpoint
    
    // HF Inference doesn't formally support multimodal arrays nicely yet in serverless 
    // unless using a specific vision model endpoint, but we serialize text to be safe.
    const messages = rawMessages.map(m => ({
      role: m.role,
      content: this._extractText(m.content)
    }));

    const body = {
      model: modelId,
      messages,
      stream: true,
      max_tokens: options.maxTokens ?? 2048,
      temperature: options.temperature ?? 0.7,
    };

    const res = await fetch(`${this.baseURL}/${modelId}/v1/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type':  'application/json'
      },
      body: JSON.stringify(body),
      signal: options.signal,
    });

    if (!res.ok) {
      let errMsg = `Hugging Face API Error ${res.status}`;
      try {
        const err = await res.json();
        errMsg = err.error || err.message || errMsg;
      } catch {}
      throw new Error(errMsg);
    }

    const reader  = res.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop(); 

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed.startsWith('data: ')) continue;
        const raw = trimmed.slice(6);
        if (raw === '[DONE]') return;

        try {
          const parsed = JSON.parse(raw);
          const delta  = parsed.choices?.[0]?.delta;
          if (delta?.content) {
            yield { content: delta.content, reasoning: '' };
          }
        } catch { /* skip malformed chunk */ }
      }
    }
  }
}
